### ISSUE TITLE
The Internet sharing shortcut on the Event view is not active.

### ISSUE THREAD

**Issue by zuyev** [piggz/droid-config-mido#1]
On the Event view after the restart the Shared Internet Access shortcut is not active. It is corrected by deleting and adding a shortcut.
![screenshot_20171021_001](https://user-images.githubusercontent.com/31903960/31849120-fc2ef720-b645-11e7-8e6d-33cae7c101ac.png)

**Comment by piggz** [comment]
This looks like a 2.1.3 bug, happens here also since upgrade. Best discussed on together.jolla.com
