### ISSUE TITLE
Can not add an account General email.

### ISSUE THREAD

**Issue by zuyev** [piggz/droid-config-mido#2]
Sailfish OS updated to version 2.1.3.5. 
Can not add an account General email and can not edit an existing account General email.

[journalctl_logcat_logs.zip](https://github.com/piggz/droid-config-mido/files/1403919/journalctl_logcat_logs.zip)

[root@Sailfish nemo]# rpm -qi droid-hal-mido
Name        : droid-hal-mido
Version     : 0.0.6
Release     : 201710111901
Architecture: armv7hl
Install Date: Wed Oct 18 02:40:20 2017
Group       : System
Size        : 33685116
License     : BSD-3-Clause
Signature   : (none)
Source RPM  : droid-hal-mido-0.0.6-201710111901.src.rpm
Build Date  : Wed Oct 11 22:02:11 2017
Build Host  : localhost.localdomain
Relocations : (not relocatable)
Vendor      : xiaomi
Summary     : Droid HAL package for mido
Description :
Droid HAL package for mido.

**Comment by piggz** [comment]
At what point does it fail?  I can start the wizard, but dont have an account to test with, but it certainly looks like it should work.

**Comment by zuyev** [comment]
OS version 2.1.2.3 - working ( i can add account General email).
After update OS to 2.1.3.5 not can add account General email.
I reinstall OS 2.1.2.3.  The Account General email add. Update OS to 2.1.3.5. I not can edit an existing account General email. And i not can add account General email. I tap General email, nothing happens.

**Comment by piggz** [comment]
Ok...sounds like its not a port problem...If we keep these bugs as hardware specific ... problems like that are best discussed at together.jolla.com i think

**Comment by zuyev** [comment]
Ok
